# Generated by Django 6.0.5 on 2026-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
